### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by AatuPitkanen** [nikolauska/teamboard-img#3]
mongoose

**Comment by nikolauska** [comment]
Database can now save and find hashed html.

Needs to be tested on real database and not on localhost

**Comment by AatuPitkanen** [comment]
Generates same hash even when board info(background, ticketposition etc.) is changed. Feature?

**Comment by nikolauska** [comment]
Might have been issue with old test jade code I made, it has now been fixed to use new info from post message

**Comment by nikolauska** [comment]
Problem found to be on rest send code which sents null json and teamboard-img added default values.

Default values has now been removed so this shouldn't occur anymore.

Bug label can be removed
